### ISSUE TITLE
使用demo发现了一个问题

### ISSUE THREAD

**Issue by senjoeson** [cai784921129/NettyDemo#2]
io.netty.channel.ConnectTimeoutException: connection timed out: /这是是我的ip:端口号
07-03 09:47:30.546 11894-11915/ifreecomm.nettydemo W/System.err:     at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:267)
07-03 09:47:30.546 11894-11915/ifreecomm.nettydemo W/System.err:     at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
07-03 09:47:30.546 11894-11915/ifreecomm.nettydemo W/System.err:     at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:125)
07-03 09:47:30.546 11894-11915/ifreecomm.nettydemo W/System.err:     at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
07-03 09:47:30.546 11894-11915/ifreecomm.nettydemo W/System.err:     at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
07-03 09:47:30.546 11894-11915/ifreecomm.nettydemo W/System.err:     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
07-03 09:47:30.546 11894-11915/ifreecomm.nettydemo W/System.err:     at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
07-03 09:47:30.546 11894-11915/ifreecomm.nettydemo W/System.err:     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
07-03 09:47:30.546 11894-11915/ifreecomm.nettydemo W/System.err:     at java.lang.Thread.run(Thread.java:761)

请问这个怎么设置呢?

**Comment by cai784921129** [comment]
请问是怎么复现的？

**Comment by senjoeson** [comment]
@cai784921129 我是直接启动你的DEMO 然后一个是模拟器 一个是我的手机  修改了你的IP  改成我电脑的IP

**Comment by cai784921129** [comment]
你用两个手机试试，别用模拟器

**Comment by senjoeson** [comment]
这个IP需要相同么?是不是只要修改app  module的const的IP就行了

**Comment by senjoeson** [comment]
我现在用2个模拟器 应该没问题了吧?

**Comment by cai784921129** [comment]
模拟器的ip不同，你一个手机开两个应用一个作为服务端，一个作为客户端

**Comment by senjoeson** [comment]
请问一下,你这个IP的设置是根据什么来定义的?

**Comment by cai784921129** [comment]
有api可以获取手机当前网络的ip地址，你也可以在手机设置看网络状态查找ip

**Comment by senjoeson** [comment]
建议你在README上面说明一下 ,刚刚测试确实是成功了

**Comment by senjoeson** [comment]
@cai784921129 大佬,和加一下QQ和你沟通学习一下么?
