### ISSUE TITLE
连接服务器成功之后 在哪里发送数据的一个问题

### ISSUE THREAD

**Issue by jasonSuzhow** [cai784921129/NettyDemo#3]
大佬你好, 就是我连接服务器成功了, 我应该在onServiceStatusConnectChanged 还是 onMessageResponse  这里发数据给服务器请求数据啊

**Comment by jasonSuzhow** [comment]
1. 在 onServiceStatusConnectChanged  的 NettyListener.STATUS_CONNECT_SUCCESS中 发送数据的话, onMessageResponse 没有数据返回.   
2. 在onMessageResponse发送能收到服务器返回的数据, 我就是怕万一没有消息返回回来怎么办

**Comment by cai784921129** [comment]
我建议在onMessageResponse 里面回复消息，首先解析服务端传来的消息数据，然后回复相应数据

**Comment by jasonSuzhow** [comment]
> 我建议在onMessageResponse 里面回复消息，首先解析服务端传来的消息数据，然后回复相应数据

好的, 谢谢

**Comment by jasonSuzhow** [comment]
还有一个问题 ,就是一个Activity1 打开另一个Activity2,  Activity1连接了TCP并在这个界面接受数据 , 我在Activity2也想连接着TCP.但是不想Activity1能接收到数据, 我应该怎么处理啊

**Comment by 29816768** [comment]
TCP客户端该怎么抽取呢  求指教
