### ISSUE TITLE
连接后无线断开重连

### ISSUE THREAD

**Issue by FirFine** [cai784921129/NettyDemo#4]
11-27 15:46:34.154 25444-26700/ifreecomm.nettydemo E/NettyClientHandler: exceptionCaught
11-27 15:46:34.155 25444-26700/ifreecomm.nettydemo W/System.err: java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)
11-27 15:46:34.156 25444-25444/ifreecomm.nettydemo E/MainActivity: onServiceStatusConnectChanged:0
11-27 15:46:34.156 25444-26700/ifreecomm.nettydemo W/System.err:     at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:595)
11-27 15:46:34.156 25444-26700/ifreecomm.nettydemo W/System.err:     at libcore.io.IoBridge.recvfrom(IoBridge.java:571)
11-27 15:46:34.156 25444-26700/ifreecomm.nettydemo W/System.err:     at java.nio.SocketChannelImpl.readImpl(SocketChannelImpl.java:342)
11-27 15:46:34.157 25444-26700/ifreecomm.nettydemo W/System.err:     at java.nio.SocketChannelImpl.read(SocketChannelImpl.java:304)
11-27 15:46:34.157 25444-26700/ifreecomm.nettydemo W/System.err:     at io.netty.buffer.UnpooledHeapByteBuf.setBytes(UnpooledHeapByteBuf.java:291)
11-27 15:46:34.157 25444-26700/ifreecomm.nettydemo W/System.err:     at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108)
11-27 15:46:34.157 25444-26700/ifreecomm.nettydemo W/System.err:     at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:345)
11-27 15:46:34.157 25444-26700/ifreecomm.nettydemo W/System.err:     at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
11-27 15:46:34.157 25444-26700/ifreecomm.nettydemo W/System.err:     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
11-27 15:46:34.157 25444-26700/ifreecomm.nettydemo W/System.err:     at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:545)
11-27 15:46:34.157 25444-26700/ifreecomm.nettydemo W/System.err:     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
11-27 15:46:34.157 25444-26700/ifreecomm.nettydemo W/System.err:     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
11-27 15:46:34.157 25444-26700/ifreecomm.nettydemo W/System.err:     at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
11-27 15:46:34.157 25444-26700/ifreecomm.nettydemo W/System.err:     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
11-27 15:46:34.157 25444-26700/ifreecomm.nettydemo W/System.err:     at java.lang.Thread.run(Thread.java:833)
11-27 15:46:34.157 25444-26700/ifreecomm.nettydemo W/System.err: Caused by: android.system.ErrnoException: recvfrom failed: ECONNRESET (Connection reset by peer)
11-27 15:46:34.157 25444-26700/ifreecomm.nettydemo W/System.err:     at libcore.io.Posix.recvfromBytes(Native Method)
11-27 15:46:34.157 25444-26700/ifreecomm.nettydemo W/System.err:     at libcore.io.Posix.recvfrom(Posix.java:181)
11-27 15:46:34.157 25444-26700/ifreecomm.nettydemo W/System.err:     at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:245)
11-27 15:46:34.157 25444-26700/ifreecomm.nettydemo W/System.err:     at libcore.io.IoBridge.recvfrom(IoBridge.java:568)
11-27 15:46:34.157 25444-26700/ifreecomm.nettydemo W/System.err: 	... 13 more
11-27 15:46:34.159 25444-25645/ifreecomm.nettydemo E/NettyTcpClient:  断开连接

**Comment by cai784921129** [comment]
无限重连？什么情况下复现的啊？

**Comment by FirFine** [comment]
我找了个回声服务器104.238.184.237，连接后就这样，是不是两边协议不一样
E/NettyTcpClient: 连接成功
E/NettyClientHandler: channelActive
E/MainActivity: STATUS_CONNECT_SUCCESS:
E/NettyClientHandler: exceptionCaught
W/System.err: java.io.IOException: Connection reset by peer
E/NettyTcpClient: 连接失败

**Comment by FirFine** [comment]
嗯，我试试吧
