### ISSUE TITLE
手机休眠后IdleStateHandler有问题

### ISSUE THREAD

**Issue by easionchang** [cai784921129/NettyDemo#5]
经测试，当手机黑屏休眠后，IdleStateHandler无法触发，当5秒钟没有发送数据时并不会触发IdleState.WRITER_IDLE事件

**Comment by cai784921129** [comment]
如果自己写定时器呢，定时器会休眠吗？

**Comment by cai784921129** [comment]
可能是Android有自己的唤醒机制， cpu休眠了。如果有心跳的需求，还是推荐用AlarmManager，来定时。
