### ISSUE TITLE
就是客户端发送，服务端能收到，但是，客户端接收不到服务器发送的数据，没进回调是怎么回事

### ISSUE THREAD

**Issue by Ronadlo7** [cai784921129/NettyDemo#7]

**Comment by cai784921129** [comment]
你用的服务端应该不是Demo中的吧，你用Demo中的就可以互相通讯。因为我设置的编解码格式是UTF-8的字符串。
` ch.pipeline().addLast(new StringEncoder(CharsetUtil.UTF_8));`
`ch.pipeline().addLast(new StringDecoder(CharsetUtil.UTF_8));`
你客户端应该是收到了，只是解码出现异常了

**Comment by Ronadlo7** [comment]
//ch.pipeline().addLast(new LineBasedFrameDecoder(1024)); 
解决了，是Demo中这句话导致先回调了channelReadComplete（），但是没回调channelRead0（），好像是说换行的原因，服务器不是Demo中的，服务器不是我写的

**Comment by cai784921129** [comment]
厉害，
ch.pipeline().addLast(new LineBasedFrameDecoder(1024));这个是用来解决TCP黏包的，我这里用的是换行作为分隔符
